// tslint:disable-next-line
export var no_tag_string = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam enim metus, condimentum et neque facilisis, pulvinar ornare ligula. Cras faucibus lectus id est ultrices, nec pulvinar erat faucibus. Phasellus mi arcu, dapibus at sodales non, fringilla sed elit. Vivamus vitae dui sodales, elementum est ac, fringilla nunc. Suspendisse potenti. Vivamus sit amet libero ut purus porta aliquet eget a nisi. Mauris massa lectus, faucibus maximus vehicula quis, laoreet porta justo. Vivamus semper quam non urna mollis efficitur. Donec faucibus lectus eu sodales imperdiet. Aliquam et aliquet libero. ';

export var string_with_tag_code = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam enim metus, condimentum et neque facilisis, pulvinar ornare ligula. Cras faucibus lectus id est ultrices, nec pulvinar erat faucibus. Phasellus mi arcu, dapibus at sodales non, fringilla sed elit. Vivamus vitae dui sodales, elementum est ac, {% nativescript %} \n ```fringilla\n ```nunc. {% endnativescript %} Suspendisse potenti. Vivamus sit amet libero ut purus porta aliquet eget a nisi. Mauris massa lectus, faucibus maximus vehicula quis, laoreet porta justo. Vivamus semper quam non urna mollis efficitur. Donec faucibus lectus eu sodales imperdiet.';

export var string_untitled_tag_code = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam enim metus, condimentum et neque facilisis, pulvinar ornare ligula. Cras faucibus lectus id est ultrices, nec pulvinar erat faucibus. Phasellus mi arcu, dapibus at sodales non, fringilla sed elit. Vivamus vitae dui sodales, elementum est ac, {% nativescript %} \n ```\n some code ```nunc. {% endnativescript %} Suspendisse potenti. Vivamus sit amet libero ut purus porta aliquet eget a nisi. Mauris massa lectus, faucibus maximus vehicula quis, laoreet porta justo. Vivamus semper quam non urna mollis efficitur. Donec faucibus lectus eu sodales imperdiet.';

export var string_with_tag = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam enim metus, condimentum et neque facilisis, pulvinar ornare ligula. Cras faucibus lectus id est ultrices, nec pulvinar erat faucibus. Phasellus mi arcu, dapibus at sodales non, fringilla sed elit. Vivamus vitae dui sodales, elementum est ac, {% nativescript %} \n fringilla nunc. {% endnativescript %} ```';

export var string_with_2_tag_code = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam enim metus, condimentum et neque facilisis, pulvinar ornare ligula. Cras faucibus lectus id est ultrices, nec pulvinar erat faucibus. Phasellus mi arcu, dapibus at sodales non, fringilla sed elit. Vivamus vitae dui sodales, elementum est ac, {% nativescript %} \n fringilla\n nunc. {% endnativescript %} Suspendisse potenti. {% nativescript %} \n ```fringilla\n ```nunc. {% endnativescript %} Vivamus semper quam non urna mollis efficitur. Donec faucibus lectus eu sodales imperdiet.';
